openapi: 3.0.1
info:
  title: hola
  description: API Definition of hola
  version: 1.0.0
servers:
- url: http://localhost:8290/hola
paths:
  /:
    get:
      responses:
        default:
          description: Default response
